version: '2'

services:
  es:
    build:
        context: .
        dockerfile: Dockerfile-es
    networks:
      elk:
        aliases:
          - elasticsearch
    volumes:
      - ./es-data:/usr/share/elasticsearch/data
    command: -Etransport.host=127.0.0.1

  kibana:
    image: kibana:5.1.1
    networks:
      - elk
    ports:
      - 5601:5601

  logstash:
    build:
        context: .
        dockerfile: Dockerfile
    networks:
      - elk
    ports:
      - 5000:5000
      - 5000:5000/udp
      - 12201:12201/udp

networks:
  elk:
    driver: bridge
