es:
  build: .
  dockerfile: Dockerfile-es
  command: -Etransport.host=127.0.0.1

kibana:
  image: kibana:5.1.1
  links: 
    - es:elasticsearch
  ports:
    - 5601:5601

logstash:
  build: .
  dockerfile: Dockerfile
  links: 
    - es:elasticsearch
  ports:
    - 5000:5000/udp
    - 5000:5000

